import { type PopupStatus } from './shared.js';

const statusText = document.getElementById('statusText') as HTMLSpanElement;
const chatgptText = document.getElementById('chatgptText') as HTMLSpanElement;
const heartbeatText = document.getElementById('heartbeatText') as HTMLSpanElement;
const pairSection = document.getElementById('pairSection') as HTMLDivElement;
const pairedSection = document.getElementById('pairedSection') as HTMLDivElement;
const pairCode = document.getElementById('pairCode') as HTMLInputElement;
const pairButton = document.getElementById('pairButton') as HTMLButtonElement;
const refreshButton = document.getElementById('refreshButton') as HTMLButtonElement;
const unpairButton = document.getElementById('unpairButton') as HTMLButtonElement;
const errorText = document.getElementById('errorText') as HTMLDivElement;

function setError(message: string | null): void {
  if (!message) {
    errorText.classList.add('hidden');
    errorText.textContent = '';
    return;
  }
  errorText.textContent = message;
  errorText.classList.remove('hidden');
}

function describeChatgpt(state: PopupStatus['chatgptState']): string {
  switch (state) {
    case 'ready':
      return 'Ready';
    case 'auth_required':
      return 'Authentication Required';
    case 'tab_not_found':
      return 'Tab Not Found';
    case 'error':
      return 'Error';
    default:
      return 'Unknown';
  }
}

async function requestStatus(): Promise<PopupStatus> {
  return await new Promise<PopupStatus>((resolve) => {
    chrome.runtime.sendMessage({ type: 'HCR_POPUP_STATUS' }, (response: PopupStatus) => {
      resolve(
        response ?? { paired: false, connected: false, lastHeartbeatAt: null, chatgptState: 'unknown', busy: false }
      );
    });
  });
}

function render(status: PopupStatus): void {
  statusText.textContent = status.paired ? (status.busy ? 'Working…' : 'Paired') : 'Not Paired';
  chatgptText.textContent = describeChatgpt(status.chatgptState);
  heartbeatText.textContent = status.lastHeartbeatAt
    ? new Date(status.lastHeartbeatAt).toLocaleTimeString()
    : '—';
  pairSection.classList.toggle('hidden', status.paired);
  pairedSection.classList.toggle('hidden', !status.paired);
}

async function refresh(): Promise<void> {
  const status = await requestStatus();
  render(status);
}

pairButton.addEventListener('click', () => {
  const code = pairCode.value.trim();
  if (code.length === 0) {
    setError('Enter the pairing code generated by HCR.');
    return;
  }
  setError(null);
  pairButton.disabled = true;
  chrome.runtime.sendMessage({ type: 'HCR_POPUP_PAIR', code }, (response: { ok?: boolean; error?: string }) => {
    pairButton.disabled = false;
    if (response?.ok) {
      pairCode.value = '';
      void refresh();
    } else {
      setError(response?.error ?? 'Pairing failed.');
    }
  });
});

refreshButton.addEventListener('click', () => {
  void refresh();
});

unpairButton.addEventListener('click', () => {
  chrome.runtime.sendMessage({ type: 'HCR_POPUP_UNPAIR' }, () => {
    void refresh();
  });
});

pairCode.addEventListener('keydown', (event) => {
  if (event.key === 'Enter') pairButton.click();
});

void refresh();
