import { type PopupActionResult, type PopupStatus, type PopupTestResult } from './shared.js';

const serverText = document.getElementById('serverText') as HTMLSpanElement;
const connectionText = document.getElementById('connectionText') as HTMLSpanElement;
const pairingText = document.getElementById('pairingText') as HTMLSpanElement;
const chatgptText = document.getElementById('chatgptText') as HTMLSpanElement;
const currentProjectText = document.getElementById('currentProjectText') as HTMLSpanElement;
const currentSessionText = document.getElementById('currentSessionText') as HTMLSpanElement;
const heartbeatText = document.getElementById('heartbeatText') as HTMLSpanElement;
const pairSection = document.getElementById('pairSection') as HTMLDivElement;
const pairedSection = document.getElementById('pairedSection') as HTMLDivElement;
const pairCode = document.getElementById('pairCode') as HTMLInputElement;
const pairButton = document.getElementById('pairButton') as HTMLButtonElement;
const testButton = document.getElementById('testButton') as HTMLButtonElement;
const unpairButton = document.getElementById('unpairButton') as HTMLButtonElement;
const testResult = document.getElementById('testResult') as HTMLDivElement;
const errorText = document.getElementById('errorText') as HTMLDivElement;

const FALLBACK_STATUS: PopupStatus = {
  paired: false,
  connected: false,
  lastHeartbeatAt: null,
  chatgptState: 'unknown',
  busy: false,
  currentProject: null,
  currentSession: null,
};

interface BackgroundReply<T> {
  value?: T;
  error?: string;
}

/**
 * Message the background service worker. `chrome.runtime.lastError` is always
 * read so the popup console stays free of "Unchecked runtime.lastError".
 */
function sendToBackground<T>(message: Record<string, unknown>): Promise<BackgroundReply<T>> {
  return new Promise((resolve) => {
    try {
      chrome.runtime.sendMessage(message, (response: T) => {
        const lastError = chrome.runtime.lastError;
        if (lastError) {
          resolve({ error: lastError.message ?? 'The extension background worker is not responding.' });
          return;
        }
        resolve({ value: response });
      });
    } catch (error) {
      resolve({ error: error instanceof Error ? error.message : 'The extension background worker is not responding.' });
    }
  });
}

function setError(message: string | null): void {
  errorText.textContent = message ?? '';
  errorText.classList.toggle('hidden', !message);
}

function setInfo(message: string | null): void {
  testResult.textContent = message ?? '';
  testResult.classList.toggle('hidden', !message);
}

function setStatusText(element: HTMLSpanElement, text: string, tone: 'ok' | 'warn' | 'none'): void {
  const dot = tone === 'none' ? '' : `<span class="dot ${tone}"></span>`;
  element.innerHTML = `${dot}${text}`;
}

function describeChatgpt(state: PopupStatus['chatgptState']): { text: string; tone: 'ok' | 'warn' | 'none' } {
  switch (state) {
    case 'ready':
      return { text: 'Ready', tone: 'ok' };
    case 'auth_required':
      return { text: 'Authentication Required', tone: 'warn' };
    case 'tab_not_found':
      return { text: 'Tab Not Found', tone: 'warn' };
    case 'error':
      return { text: 'Error', tone: 'warn' };
    default:
      return { text: 'Unknown', tone: 'none' };
  }
}

function render(status: PopupStatus): void {
  setStatusText(connectionText, status.connected ? 'Connected' : 'Not Connected', status.connected ? 'ok' : 'warn');
  setStatusText(pairingText, status.paired ? 'Paired' : 'Not Paired', status.paired ? 'ok' : 'warn');
  const chatgpt = describeChatgpt(status.chatgptState);
  setStatusText(chatgptText, chatgpt.text, chatgpt.tone);
  // Never guessed: Unknown unless the adapter recognized the destination.
  currentProjectText.textContent = status.currentProject ?? 'Unknown';
  currentSessionText.textContent = status.currentSession ?? 'Unknown';
  heartbeatText.textContent = status.lastHeartbeatAt
    ? new Date(status.lastHeartbeatAt).toLocaleTimeString()
    : '—';
  pairSection.classList.toggle('hidden', status.paired);
  pairedSection.classList.toggle('hidden', !status.paired);
}

async function refresh(): Promise<void> {
  const { value, error } = await sendToBackground<PopupStatus>({ type: 'HCR_POPUP_STATUS' });
  render(value ?? FALLBACK_STATUS);
  if (error) setError(error);
}

pairButton.addEventListener('click', () => {
  const code = pairCode.value.trim();
  if (code.length === 0) {
    setError('Enter the pairing code generated by HCR.');
    return;
  }
  setError(null);
  setInfo(null);
  pairButton.disabled = true;
  void (async () => {
    const { value, error } = await sendToBackground<PopupActionResult>({ type: 'HCR_POPUP_PAIR', code });
    pairButton.disabled = false;
    if (error) {
      setError(error);
      return;
    }
    if (value?.ok) {
      pairCode.value = '';
      setInfo('Paired with HCR. Heartbeats are running.');
      await refresh();
      return;
    }
    setError(value?.error ?? 'Pairing failed.');
  })();
});

testButton.addEventListener('click', () => {
  setError(null);
  setInfo(null);
  testButton.disabled = true;
  void (async () => {
    const { value, error } = await sendToBackground<PopupTestResult>({ type: 'HCR_POPUP_TEST' });
    testButton.disabled = false;
    if (error) {
      setError(error);
      return;
    }
    if (value?.ok) {
      const seen = value.lastSeenAt ? new Date(value.lastSeenAt).toLocaleTimeString() : 'never';
      setInfo(
        `HCR reachable · ${value.paired ? 'paired' : 'not paired'} · last seen ${seen} · ${
          value.queuedTasks ?? 0
        } queued task(s)`
      );
      await refresh();
      return;
    }
    setError(value?.error ?? 'Could not reach HCR.');
  })();
});

unpairButton.addEventListener('click', () => {
  setError(null);
  setInfo(null);
  void (async () => {
    const { error } = await sendToBackground<PopupActionResult>({ type: 'HCR_POPUP_UNPAIR' });
    if (error) {
      setError(error);
      return;
    }
    setInfo('Unpaired. Generate a new pairing code in HCR to pair again.');
    await refresh();
  })();
});

pairCode.addEventListener('keydown', (event) => {
  if (event.key === 'Enter') pairButton.click();
});

serverText.textContent = '127.0.0.1:7876';
void refresh();
