import type { FastifyInstance, FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import type { CompanionStage, CompanionStatus, CompanionTaskResult } from '@heisenberg/contracts';
import type { AppContext } from '../context.js';
import { AppError } from '@heisenberg/shared';

const TOKEN_HEADER = 'x-hcr-companion-token';
const STAGES: CompanionStage[] = [
  'waiting_for_browser',
  'opening_chatgpt',
  'sending_prompt',
  'waiting_for_response',
  'receiving_response',
];

const ALLOWED_ORIGINS = [
  /^chrome-extension:\/\//,
  /^ms-browser-extension:\/\//,
  /^moz-extension:\/\//,
  /^http:\/\/127\.0\.0\.1(:\d+)?$/,
  /^http:\/\/localhost(:\d+)?$/,
];

/**
 * Explicit request contracts, validated by Fastify before a handler runs.
 *
 * Fastify rejects `Content-Type: application/json` with an empty body, so
 * payload-less POSTs send `{}` instead of nothing. `nullable` additionally
 * accepts a completely absent body (plain `curl -X POST`) so the handler can
 * answer with its own friendly message ("Pairing code is required") instead of
 * a generic schema error. Unknown properties are dropped by Fastify's default
 * `removeAdditional`, never rejected, so newer extension builds keep working.
 *
 * Value-level checks (which stage/status strings are allowed) stay in the
 * handlers so the 400 message lists the accepted values.
 */

/** Endpoints that take no input: accept no body or `{}`. */
const NO_PAYLOAD_BODY = {
  nullable: true,
  type: 'object',
  additionalProperties: false,
  properties: {},
} as const;

/** POST /api/browser-companion/pair -> `{ "code": "ABCD1234" }` */
const PAIR_BODY = {
  nullable: true,
  type: 'object',
  additionalProperties: false,
  properties: { code: { type: 'string' } },
} as const;

/** POST /api/browser-companion/heartbeat -> `{ "chatgpt": { "state", "detail" } }` */
const HEARTBEAT_BODY = {
  nullable: true,
  type: 'object',
  additionalProperties: false,
  properties: {
    chatgpt: {
      type: 'object',
      additionalProperties: false,
      properties: {
        state: { type: 'string' },
        detail: { type: ['string', 'null'] },
      },
    },
  },
} as const;

/** POST /api/browser-companion/task/:id/stage -> `{ "stage": "..." }` */
const STAGE_BODY = {
  nullable: true,
  type: 'object',
  additionalProperties: false,
  properties: { stage: { type: 'string' } },
} as const;

/** POST /api/browser-companion/task/:id/result -> `{ "status", "responseText"?, "message"?, "chatgptState"? }` */
const RESULT_BODY = {
  nullable: true,
  type: 'object',
  additionalProperties: false,
  properties: {
    status: { type: 'string' },
    responseText: { type: 'string' },
    message: { type: 'string' },
    chatgptState: { type: 'string' },
  },
} as const;

function tokenFrom(request: FastifyRequest): string | null {
  const header = request.headers[TOKEN_HEADER];
  if (typeof header === 'string' && header.length > 0) return header;
  const auth = request.headers.authorization;
  if (typeof auth === 'string' && auth.toLowerCase().startsWith('bearer ')) return auth.slice(7).trim();
  return null;
}

/**
 * Browser Companion control plane.
 *
 * Every endpoint that lets the extension act on HCR requires the local
 * pairing secret. The secret is generated by HCR, exchanged once through a
 * short-lived pairing code, and never leaves the machine. CORS is enabled
 * only inside this encapsulated scope.
 */
export async function registerBrowserCompanionRoutes(app: FastifyInstance, context: AppContext): Promise<void> {
  const { companion } = context;

  const requireToken = (request: FastifyRequest): void => {
    companion.requireToken(tokenFrom(request));
  };

  await app.register(async (scope) => {
    await scope.register(cors, {
      origin(origin, callback) {
        if (!origin) return callback(null, true);
        callback(null, ALLOWED_ORIGINS.some((pattern) => pattern.test(origin)));
      },
      methods: ['GET', 'POST', 'OPTIONS'],
      allowedHeaders: ['Content-Type', TOKEN_HEADER, 'Authorization'],
    });

    // ---- status (dashboard, no token) ------------------------------- //

    scope.get('/api/browser-companion/status', async (): Promise<CompanionStatus> => {
      return companion.status();
    });

    // ---- pairing ---------------------------------------------------- //

    scope.post(
      '/api/browser-companion/pairing-code',
      { schema: { body: NO_PAYLOAD_BODY } },
      async () => {
        const { code, expiresAt } = companion.generatePairingCode();
        return {
          code,
          expiresAt,
          instructions: [
            'Download and load the HCR Browser Companion extension.',
            'Open the extension popup and paste this pairing code.',
            'The extension stores the local pairing secret and starts heartbeating.',
          ],
        };
      }
    );

    scope.post('/api/browser-companion/pair', { schema: { body: PAIR_BODY } }, async (request) => {
      const { code } = (request.body ?? {}) as { code?: string };
      if (!code || code.trim().length === 0) {
        throw new AppError('Pairing code is required', 400);
      }
      const paired = companion.pair(code);
      return {
        paired: true,
        token: paired.token,
        provider: 'chatgpt-web',
        message: 'Paired with HCR. The token is stored only in the extension.',
      };
    });

    // Deliberate reset: rotates the local pairing secret (extension re-pairs).
    scope.post(
      '/api/browser-companion/reset',
      { schema: { body: NO_PAYLOAD_BODY } },
      async () => {
        companion.reset();
        return { reset: true, paired: false };
      }
    );

    scope.post(
      '/api/browser-companion/test',
      { schema: { body: NO_PAYLOAD_BODY } },
      async () => {
        const status = companion.status();
        return {
          connected: status.connected,
          paired: status.paired,
          lastSeenAt: status.lastSeenAt,
          queuedTasks: companion.queuedTaskCount(),
        };
      }
    );

    // ---- authenticated companion endpoints -------------------------- //
    // The token check runs in `preValidation`, i.e. before body schema
    // validation, so an unauthorized request is always answered with 401 and
    // never leaks whether its body would have been valid.

    scope.post(
      '/api/browser-companion/heartbeat',
      { preValidation: requireToken, schema: { body: HEARTBEAT_BODY } },
      async (request) => {
        const body = (request.body ?? {}) as {
          chatgpt?: { state?: CompanionStatus['chatgpt']['state']; detail?: string | null };
        };
        if (body.chatgpt?.state) {
          companion.reportChatgptState(body.chatgpt.state, body.chatgpt.detail ?? null);
        }
        const beat = companion.heartbeat();
        return {
          ok: true,
          lastSeenAt: beat.lastSeenAt,
          task: companion.takeTask(),
        };
      }
    );

    scope.get('/api/browser-companion/task', { preValidation: requireToken }, async () => {
      return { task: companion.takeTask() };
    });

    scope.post(
      '/api/browser-companion/task/:id/stage',
      { preValidation: requireToken, schema: { body: STAGE_BODY } },
      async (request) => {
        const { id } = request.params as { id: string };
        const { stage } = (request.body ?? {}) as { stage?: string };
        if (!stage || !STAGES.includes(stage as CompanionStage)) {
          throw new AppError(`stage must be one of: ${STAGES.join(', ')}`, 400);
        }
        if (!companion.hasTask(id)) {
          throw new AppError('Unknown or expired companion task', 404);
        }
        companion.setStage(id, stage as CompanionStage);
        return { ok: true };
      }
    );

    scope.post(
      '/api/browser-companion/task/:id/result',
      { preValidation: requireToken, schema: { body: RESULT_BODY } },
      async (request) => {
        const { id } = request.params as { id: string };
        const body = (request.body ?? {}) as { status?: string; responseText?: string; message?: string };
        const status = body.status;
        if (
          status !== 'OK' &&
          status !== 'AUTH_REQUIRED' &&
          status !== 'NO_TAB' &&
          status !== 'TIMEOUT' &&
          status !== 'ERROR'
        ) {
          throw new AppError('status must be OK | AUTH_REQUIRED | NO_TAB | TIMEOUT | ERROR', 400);
        }
        const result: CompanionTaskResult =
          status === 'OK'
            ? { status: 'OK', responseText: typeof body.responseText === 'string' ? body.responseText : '' }
            : { status, message: typeof body.message === 'string' ? body.message : undefined };

        const handoffId = await companion.resolveTask(id, result);
        if (!handoffId) {
          // Unknown/expired task: acknowledge so the extension can move on.
          return { ok: true, handoffId: null, note: 'Task was no longer queued.' };
        }
        return { ok: true, handoffId };
      }
    );
  });
}
